import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { Providers } from "./providers";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashgo.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        
        <body className={`${roboto.className}`}>
          <Providers>{children}</Providers>
        </body>
      </html>
  );
}
